name: miki
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  path: ^1.9.1
  sqflite: ^2.4.2
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0  # Gráficos para estadísticas
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/login.jpg
    - assets/creacionCuenta.jpg
    - assets/BuscarCorreo.jpg
    - assets/restablerContra.jpg
    - assets/mapa.png
    - assets/usa.png
    - assets/honduras.png
    - assets/brasil.png
    - assets/espana.png
    - assets/japon.png
    - assets/vietnam.png
    - assets/producto1.png
    - assets/producto2.png
    - assets/producto3.png
    - assets/venta.png
    - assets/gasto.png
    - assets/inventario.png
    - assets/argentina.png
    - assets/colombia.png
    - assets/peru.png
    - assets/mexico.png